-- =============================================================================
-- PROYECTO: SAMANYA OS
-- ARCHIVO: build_all.sql
-- DESCRIPCIÓN: Script maestro orquestador de compilación PL/SQL.
--              Invoca secuencialmente cada uno de los 116 artefactos PL/SQL
--              en su estricto orden lógico de dependencias utilizando directivas relativas "@@".
--              Compatible con SQL*Plus, SQLcl, Oracle SQL Developer y scripts de migración.
--
--              Estructura Arquitectónica de Artefactos (116 objetos):
--              - 2 Utilidades base de fecha y transacciones (f_fecha_actual.sql, p_do_commit.sql)
--              - 91 Paquetes DAO de acceso a datos por PK/ROWID (pkgsmy_*_dao.sql)
--              - 1 Paquete de utilidades de excepciones y logging (uti_ge_excepciones_pkg.sql)
--              - 6 Paquetes de consultas, filtros y DML no-PK (pkgca_residentes, pkgca_smy_usuarios, pkgca_smy_dispositivos_push, pkgca_smy_consentimientos, pkgca_smy_archivos, pkgca_smy_residente_acudiente)
--              - 6 Paquetes DML/JSON de proceso multi-tabla (pkgcn_auth, pkgcn_consentimientos, pkgcn_archivos, pkgcn_superadmin, pkgcn_dashboard_administrador, pkgcn_cuadrantes_turnos)
--              - 10 Paquetes de Lógica de Negocio con COMMIT (pkgln_archivos, pkgln_auth, pkgln_consentimientos, pkgln_superadmin, pkgln_dashboard_administrador, pkgln_admision_residente, pkgln_gestion_familiares, pkgln_talento_humano, pkgln_cuadrantes_turnos, pkgln_permisos_ausencias)
--              - 1 Bloque final de verificación y reporte de objetos inválidos en USER_OBJECTS
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK ON;
SET VERIFY OFF;
SET LINESIZE 200;
SET PAGESIZE 100;

-- -----------------------------------------------------------------------------
-- INICIO DE COMPILACIÓN Y REGISTRO DE HORA OFICIAL (UTC-5 Bogotá)
-- -----------------------------------------------------------------------------
DECLARE
    v_fecha_bogota VARCHAR2(50);
BEGIN
    SELECT TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE 'America/Bogota' AS DATE), 'YYYY-MM-DD HH24:MI:SS')
      INTO v_fecha_bogota
      FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('============================================================================');
    DBMS_OUTPUT.PUT_LINE('  INICIANDO COMPILACIÓN COMPLETA DE ARTEFACTOS PL/SQL - SAMANYA OS');
    DBMS_OUTPUT.PUT_LINE('  TOTAL OBJETOS A COMPILAR: 116');
    DBMS_OUTPUT.PUT_LINE('  HORA OFICIAL (Bogotá, Colombia - UTC-5): ' || v_fecha_bogota);
    DBMS_OUTPUT.PUT_LINE('============================================================================');
END;
/

PROMPT
PROMPT ============================================================================
PROMPT [1/6] COMPILANDO FUNCIONES Y UTILIDADES BASE
PROMPT ============================================================================
PROMPT >> Compilando f_fecha_actual.sql...
@@f_fecha_actual.sql
PROMPT >> Compilando p_do_commit.sql...
@@p_do_commit.sql

PROMPT
PROMPT ============================================================================
PROMPT [2/6] COMPILANDO CAPA DE ACCESO A DATOS (91 PAQUETES DAO)
PROMPT ============================================================================
PROMPT >> Compilando pkgsmy_estados_organizaciones_dao.sql...
@@pkgsmy_estados_organizaciones_dao.sql
PROMPT >> Compilando pkgsmy_organizaciones_dao.sql...
@@pkgsmy_organizaciones_dao.sql
PROMPT >> [03/101] Compilando pkgsmy_acudientes_dao.sql...
@@pkgsmy_acudientes_dao.sql
PROMPT >> [04/101] Compilando pkgsmy_alcances_tareas_dao.sql...
@@pkgsmy_alcances_tareas_dao.sql
PROMPT >> [05/101] Compilando pkgsmy_archivos_dao.sql...
@@pkgsmy_archivos_dao.sql
PROMPT >> [06/101] Compilando pkgsmy_areas_empleados_dao.sql...
@@pkgsmy_areas_empleados_dao.sql
PROMPT >> [07/101] Compilando pkgsmy_auditoria_accesos_dao.sql...
@@pkgsmy_auditoria_accesos_dao.sql
PROMPT >> [08/101] Compilando pkgsmy_bitacora_residente_dao.sql...
@@pkgsmy_bitacora_residente_dao.sql
PROMPT >> [09/101] Compilando pkgsmy_canales_notificacion_dao.sql...
@@pkgsmy_canales_notificacion_dao.sql
PROMPT >> [10/101] Compilando pkgsmy_cargos_empleados_dao.sql...
@@pkgsmy_cargos_empleados_dao.sql
PROMPT >> [11/101] Compilando pkgsmy_categorias_bitacora_dao.sql...
@@pkgsmy_categorias_bitacora_dao.sql
PROMPT >> [12/101] Compilando pkgsmy_categorias_doc_clinicos_dao.sql...
@@pkgsmy_categorias_doc_clinicos_dao.sql
PROMPT >> Compilando pkgsmy_centros_dao.sql...
@@pkgsmy_centros_dao.sql
PROMPT >> Compilando pkgsmy_centro_usuarios_dao.sql...
@@pkgsmy_centro_usuarios_dao.sql
PROMPT >> Compilando pkgsmy_chat_participantes_dao.sql...
@@pkgsmy_chat_participantes_dao.sql
PROMPT >> [15/101] Compilando pkgsmy_clases_archivos_dao.sql...
@@pkgsmy_clases_archivos_dao.sql
PROMPT >> [16/101] Compilando pkgsmy_consentimiento_destinatarios_dao.sql...
@@pkgsmy_consentimiento_destinatarios_dao.sql
PROMPT >> [17/101] Compilando pkgsmy_consentimientos_dao.sql...
@@pkgsmy_consentimientos_dao.sql
PROMPT >> [18/101] Compilando pkgsmy_consistencias_dieta_dao.sql...
@@pkgsmy_consistencias_dieta_dao.sql
PROMPT >> [19/101] Compilando pkgsmy_conversaciones_chat_dao.sql...
@@pkgsmy_conversaciones_chat_dao.sql
PROMPT >> [20/101] Compilando pkgsmy_dispositivos_push_dao.sql...
@@pkgsmy_dispositivos_push_dao.sql
PROMPT >> [21/101] Compilando pkgsmy_documentos_clinicos_dao.sql...
@@pkgsmy_documentos_clinicos_dao.sql
PROMPT >> [22/101] Compilando pkgsmy_documentos_eliminados_log_dao.sql...
@@pkgsmy_documentos_eliminados_log_dao.sql
PROMPT >> [23/101] Compilando pkgsmy_documentos_empleado_dao.sql...
@@pkgsmy_documentos_empleado_dao.sql
PROMPT >> [24/101] Compilando pkgsmy_empleados_dao.sql...
@@pkgsmy_empleados_dao.sql
PROMPT >> [25/101] Compilando pkgsmy_errores_dao.sql...
@@pkgsmy_errores_dao.sql
PROMPT >> [26/101] Compilando pkgsmy_estados_admin_med_dao.sql...
@@pkgsmy_estados_admin_med_dao.sql
PROMPT >> [27/101] Compilando pkgsmy_estados_archivos_dao.sql...
@@pkgsmy_estados_archivos_dao.sql
PROMPT >> [28/101] Compilando pkgsmy_estados_consentimientos_dao.sql...
@@pkgsmy_estados_consentimientos_dao.sql
PROMPT >> [29/101] Compilando pkgsmy_estados_doc_clinicos_dao.sql...
@@pkgsmy_estados_doc_clinicos_dao.sql
PROMPT >> Compilando pkgsmy_estados_empleados_dao.sql...
@@pkgsmy_estados_empleados_dao.sql
PROMPT >> Compilando pkgsmy_estados_firmas_cons_dao.sql...
@@pkgsmy_estados_firmas_cons_dao.sql
PROMPT >> [32/101] Compilando pkgsmy_estados_incidentes_dao.sql...
@@pkgsmy_estados_incidentes_dao.sql
PROMPT >> [33/101] Compilando pkgsmy_estados_medicamentos_dao.sql...
@@pkgsmy_estados_medicamentos_dao.sql
PROMPT >> [34/101] Compilando pkgsmy_estados_pagos_dao.sql...
@@pkgsmy_estados_pagos_dao.sql
PROMPT >> [35/101] Compilando pkgsmy_estados_parametros_dao.sql...
@@pkgsmy_estados_parametros_dao.sql
PROMPT >> [36/101] Compilando pkgsmy_estados_permisos_dao.sql...
@@pkgsmy_estados_permisos_dao.sql
PROMPT >> [37/101] Compilando pkgsmy_estados_plantillas_turno_dao.sql...
@@pkgsmy_estados_plantillas_turno_dao.sql
PROMPT >> [38/101] Compilando pkgsmy_estados_residentes_dao.sql...
@@pkgsmy_estados_residentes_dao.sql
PROMPT >> [39/101] Compilando pkgsmy_estados_roles_dao.sql...
@@pkgsmy_estados_roles_dao.sql
PROMPT >> [40/101] Compilando pkgsmy_estados_solicitudes_adm_dao.sql...
@@pkgsmy_estados_solicitudes_adm_dao.sql
PROMPT >> [41/101] Compilando pkgsmy_estados_tareas_dao.sql...
@@pkgsmy_estados_tareas_dao.sql
PROMPT >> [42/101] Compilando pkgsmy_estados_turnos_dao.sql...
@@pkgsmy_estados_turnos_dao.sql
PROMPT >> [43/101] Compilando pkgsmy_estados_usuarios_dao.sql...
@@pkgsmy_estados_usuarios_dao.sql
PROMPT >> [44/101] Compilando pkgsmy_eventos_calendario_dao.sql...
@@pkgsmy_eventos_calendario_dao.sql
PROMPT >> [45/101] Compilando pkgsmy_generos_dao.sql...
@@pkgsmy_generos_dao.sql
PROMPT >> [46/101] Compilando pkgsmy_historias_clinicas_dao.sql...
@@pkgsmy_historias_clinicas_dao.sql
PROMPT >> [47/101] Compilando pkgsmy_incidente_residentes_dao.sql...
@@pkgsmy_incidente_residentes_dao.sql
PROMPT >> [48/101] Compilando pkgsmy_incidentes_dao.sql...
@@pkgsmy_incidentes_dao.sql
PROMPT >> [49/101] Compilando pkgsmy_medicamentos_prescritos_dao.sql...
@@pkgsmy_medicamentos_prescritos_dao.sql
PROMPT >> [50/101] Compilando pkgsmy_mensajes_chat_dao.sql...
@@pkgsmy_mensajes_chat_dao.sql
PROMPT >> [51/101] Compilando pkgsmy_niveles_movilidad_dao.sql...
@@pkgsmy_niveles_movilidad_dao.sql
PROMPT >> Compilando pkgsmy_notificaciones_sistema_dao.sql...
@@pkgsmy_notificaciones_sistema_dao.sql
PROMPT >> Compilando pkgsmy_organizacion_duenos_dao.sql...
@@pkgsmy_organizacion_duenos_dao.sql
PROMPT >> Compilando pkgsmy_parametros_dao.sql...
@@pkgsmy_parametros_dao.sql
PROMPT >> [54/101] Compilando pkgsmy_parentescos_dao.sql...
@@pkgsmy_parentescos_dao.sql
PROMPT >> [55/101] Compilando pkgsmy_planes_nutricionales_dao.sql...
@@pkgsmy_planes_nutricionales_dao.sql
PROMPT >> [56/101] Compilando pkgsmy_plantillas_turno_dao.sql...
@@pkgsmy_plantillas_turno_dao.sql
PROMPT >> [57/101] Compilando pkgsmy_registros_admin_med_dao.sql...
@@pkgsmy_registros_admin_med_dao.sql
PROMPT >> [58/101] Compilando pkgsmy_registros_alim_detalle_dao.sql...
@@pkgsmy_registros_alim_detalle_dao.sql
PROMPT >> [59/101] Compilando pkgsmy_registros_alim_sesion_dao.sql...
@@pkgsmy_registros_alim_sesion_dao.sql
PROMPT >> [60/101] Compilando pkgsmy_residente_acudiente_dao.sql...
@@pkgsmy_residente_acudiente_dao.sql
PROMPT >> [61/101] Compilando pkgsmy_residentes_dao.sql...
@@pkgsmy_residentes_dao.sql
PROMPT >> [62/101] Compilando pkgsmy_roles_dao.sql...
@@pkgsmy_roles_dao.sql
PROMPT >> [63/101] Compilando pkgsmy_roles_en_incidente_dao.sql...
@@pkgsmy_roles_en_incidente_dao.sql
PROMPT >> [64/101] Compilando pkgsmy_severidades_incidentes_dao.sql...
@@pkgsmy_severidades_incidentes_dao.sql
PROMPT >> [65/101] Compilando pkgsmy_signos_vitales_dao.sql...
@@pkgsmy_signos_vitales_dao.sql
PROMPT >> [66/101] Compilando pkgsmy_solicitud_adm_contactos_dao.sql...
@@pkgsmy_solicitud_adm_contactos_dao.sql
PROMPT >> [67/101] Compilando pkgsmy_solicitudes_admision_dao.sql...
@@pkgsmy_solicitudes_admision_dao.sql
PROMPT >> [68/101] Compilando pkgsmy_solicitudes_permisos_dao.sql...
@@pkgsmy_solicitudes_permisos_dao.sql
PROMPT >> [69/101] Compilando pkgsmy_suministros_registro_dao.sql...
@@pkgsmy_suministros_registro_dao.sql
PROMPT >> [70/101] Compilando pkgsmy_tarea_residentes_dao.sql...
@@pkgsmy_tarea_residentes_dao.sql
PROMPT >> [71/101] Compilando pkgsmy_tareas_operativas_dao.sql...
@@pkgsmy_tareas_operativas_dao.sql
PROMPT >> [72/101] Compilando pkgsmy_tipos_adjuntos_chat_dao.sql...
@@pkgsmy_tipos_adjuntos_chat_dao.sql
PROMPT >> [73/101] Compilando pkgsmy_tipos_archivos_doc_dao.sql...
@@pkgsmy_tipos_archivos_doc_dao.sql
PROMPT >> [74/101] Compilando pkgsmy_tipos_canales_chat_dao.sql...
@@pkgsmy_tipos_canales_chat_dao.sql
PROMPT >> [75/101] Compilando pkgsmy_tipos_comidas_dao.sql...
@@pkgsmy_tipos_comidas_dao.sql
PROMPT >> [76/101] Compilando pkgsmy_tipos_consentimientos_dao.sql...
@@pkgsmy_tipos_consentimientos_dao.sql
PROMPT >> [77/101] Compilando pkgsmy_tipos_dietas_dao.sql...
@@pkgsmy_tipos_dietas_dao.sql
PROMPT >> [78/101] Compilando pkgsmy_tipos_entradas_doc_dao.sql...
@@pkgsmy_tipos_entradas_doc_dao.sql
PROMPT >> [79/101] Compilando pkgsmy_tipos_eventos_dao.sql...
@@pkgsmy_tipos_eventos_dao.sql
PROMPT >> [80/101] Compilando pkgsmy_tipos_identificacion_dao.sql...
@@pkgsmy_tipos_identificacion_dao.sql
PROMPT >> [81/101] Compilando pkgsmy_tipos_incidentes_dao.sql...
@@pkgsmy_tipos_incidentes_dao.sql
PROMPT >> [82/101] Compilando pkgsmy_tipos_notificaciones_dao.sql...
@@pkgsmy_tipos_notificaciones_dao.sql
PROMPT >> [83/101] Compilando pkgsmy_tipos_permisos_dao.sql...
@@pkgsmy_tipos_permisos_dao.sql
PROMPT >> [84/101] Compilando pkgsmy_tipos_suministros_dao.sql...
@@pkgsmy_tipos_suministros_dao.sql
PROMPT >> [85/101] Compilando pkgsmy_tipos_tareas_dao.sql...
@@pkgsmy_tipos_tareas_dao.sql
PROMPT >> [86/101] Compilando pkgsmy_tipos_usuarios_dao.sql...
@@pkgsmy_tipos_usuarios_dao.sql
PROMPT >> [87/101] Compilando pkgsmy_turnos_asignados_dao.sql...
@@pkgsmy_turnos_asignados_dao.sql
PROMPT >> [88/101] Compilando pkgsmy_usuarios_dao.sql...
@@pkgsmy_usuarios_dao.sql
PROMPT >> [89/101] Compilando pkgsmy_vias_administracion_dao.sql...
@@pkgsmy_vias_administracion_dao.sql

PROMPT
PROMPT ============================================================================
PROMPT [3/6] COMPILANDO PAQUETE DE GESTIÓN DE EXCEPCIONES Y LOGGING
PROMPT ============================================================================
PROMPT >> [90/101] Compilando uti_ge_excepciones_pkg.sql...
@@uti_ge_excepciones_pkg.sql

PROMPT
PROMPT ============================================================================
PROMPT [4/6] COMPILANDO CAPA DE CONSULTAS Y FILTROS (PKGCA)
PROMPT ============================================================================
PROMPT >> [91/101] Compilando pkgca_residentes.sql...
@@pkgca_residentes.sql
PROMPT >> [92/101] Compilando pkgca_smy_usuarios.sql...
@@pkgca_smy_usuarios.sql
PROMPT >> [93/101] Compilando pkgca_smy_dispositivos_push.sql...
@@pkgca_smy_dispositivos_push.sql
PROMPT >> [94/101] Compilando pkgca_smy_consentimientos.sql...
@@pkgca_smy_consentimientos.sql
PROMPT >> [95/101] Compilando pkgca_smy_archivos.sql...
@@pkgca_smy_archivos.sql
PROMPT >> Compilando pkgca_smy_residente_acudiente.sql...
@@pkgca_smy_residente_acudiente.sql

PROMPT
PROMPT ============================================================================
PROMPT [5/6] COMPILANDO CAPA DML MULTI-TABLA DE PROCESO (PKGCN)
PROMPT ============================================================================
PROMPT >> Compilando pkgcn_auth.sql...
@@pkgcn_auth.sql
PROMPT >> Compilando pkgcn_consentimientos.sql...
@@pkgcn_consentimientos.sql
PROMPT >> Compilando pkgcn_archivos.sql...
@@pkgcn_archivos.sql
PROMPT >> Compilando pkgcn_superadmin.sql...
@@pkgcn_superadmin.sql
PROMPT >> Compilando pkgcn_dashboard_administrador.sql...
@@pkgcn_dashboard_administrador.sql
PROMPT >> Compilando pkgcn_cuadrantes_turnos.sql...
@@pkgcn_cuadrantes_turnos.sql

PROMPT
PROMPT ============================================================================
PROMPT [6/6] COMPILANDO CAPA DE LÓGICA DE NEGOCIO Y TRANSACCIONES (PKGLN)
PROMPT ============================================================================
PROMPT >> Compilando pkgln_archivos.sql...
@@pkgln_archivos.sql
PROMPT >> Compilando pkgln_auth.sql...
@@pkgln_auth.sql
PROMPT >> Compilando pkgln_consentimientos.sql...
@@pkgln_consentimientos.sql
PROMPT >> Compilando pkgln_superadmin.sql...
@@pkgln_superadmin.sql
PROMPT >> Compilando pkgln_dashboard_administrador.sql...
@@pkgln_dashboard_administrador.sql
PROMPT >> Compilando pkgln_admision_residente.sql...
@@pkgln_admision_residente.sql
PROMPT >> Compilando pkgln_gestion_familiares.sql...
@@pkgln_gestion_familiares.sql
PROMPT >> Compilando pkgln_talento_humano.sql...
@@pkgln_talento_humano.sql
PROMPT >> Compilando pkgln_cuadrantes_turnos.sql...
@@pkgln_cuadrantes_turnos.sql
PROMPT >> Compilando pkgln_permisos_ausencias.sql...
@@pkgln_permisos_ausencias.sql

PROMPT
PROMPT ============================================================================
PROMPT VALIDACIÓN DE ESTADO Y OBJETOS INVÁLIDOS EN EL ESQUEMA
PROMPT ============================================================================
DECLARE
    vn_invalidos NUMBER := 0;
BEGIN
    FOR reg IN (
        SELECT object_type, object_name, status
          FROM user_objects
         WHERE status = 'INVALID'
           AND (object_name LIKE 'PKGSMY_%_DAO' 
                OR object_name LIKE 'PKGCA_%' 
                OR object_name LIKE 'PKGCN_%'
                OR object_name LIKE 'PKGLN_%'
                OR object_name = 'UTI_GE_EXCEPCIONES_PKG'
                OR object_name = 'F_FECHA_ACTUAL'
                OR object_name = 'P_DO_COMMIT')
         ORDER BY object_type, object_name
    ) LOOP
        vn_invalidos := vn_invalidos + 1;
        DBMS_OUTPUT.PUT_LINE('  ALERTA: Objeto ' || reg.object_type || ' ' || reg.object_name || ' tiene estado ' || reg.status);
    END LOOP;

    IF vn_invalidos = 0 THEN
        DBMS_OUTPUT.PUT_LINE('============================================================================');
        DBMS_OUTPUT.PUT_LINE('  OK: Todos los 116 objetos PL/SQL se encuentran en estado VALID.');
        DBMS_OUTPUT.PUT_LINE('============================================================================');
    ELSE
        DBMS_OUTPUT.PUT_LINE('============================================================================');
        DBMS_OUTPUT.PUT_LINE('  ATENCIÓN: Se detectaron ' || vn_invalidos || ' objetos en estado INVALID.');
        DBMS_OUTPUT.PUT_LINE('============================================================================');
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- RESUMEN FINAL DE COMPILACIÓN
-- -----------------------------------------------------------------------------
DECLARE
    v_fecha_fin VARCHAR2(50);
BEGIN
    SELECT TO_CHAR(f_fecha_actual, 'YYYY-MM-DD HH24:MI:SS')
      INTO v_fecha_fin
      FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('============================================================================');
    DBMS_OUTPUT.PUT_LINE('  COMPILACIÓN COMPLETADA - HORA BOGOTÁ (UTC-5): ' || v_fecha_fin);
    DBMS_OUTPUT.PUT_LINE('  Total objetos orquestados: 116');
    DBMS_OUTPUT.PUT_LINE('  (2 Utilidades Base + 91 DAOs + 1 Utilidad Logging + 6 Consultas/DML PKGCA + 6 DML/JSON Multi-Tabla PKGCN + 10 Lógica de Negocio PKGLN)');
    DBMS_OUTPUT.PUT_LINE('============================================================================');
END;
/
